# Generated by Django 4.2.11 on 2026-03-24 08:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('working', 'Working'), ('damaged', 'Damaged'), ('under_repair', 'Under Repair')], default='working', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Unit',
                'verbose_name_plural': 'Device Units',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('working', 'Working'), ('damaged', 'Damaged'), ('under_repair', 'Under Repair')], default='working', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_by', models.CharField(max_length=200)),
                ('problem', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=200, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('device_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='inventory.deviceunit')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='inventory.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='inventory.location')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-raised_at'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='deviceunit',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_units', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='deviceunit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_units', to='inventory.location'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('issue_reported', 'Issue Reported'), ('repair_completed', 'Repair Completed'), ('item_transferred', 'Item Transferred'), ('item_added', 'Item Added'), ('item_updated', 'Item Updated'), ('item_deleted', 'Item Deleted')], max_length=50)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='inventory.item')),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='inventory_i_name_637656_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='inventory_i_status_25f563_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['location'], name='inventory_i_locatio_873418_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceunit',
            index=models.Index(fields=['serial_number'], name='inventory_d_serial__ab7e91_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceunit',
            index=models.Index(fields=['item'], name='inventory_d_item_id_90324a_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceunit',
            index=models.Index(fields=['status'], name='inventory_d_status_a798ae_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceunit',
            index=models.Index(fields=['location'], name='inventory_d_locatio_49cf85_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['item'], name='inventory_a_item_id_7f51f6_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='inventory_a_action_c8fb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='inventory_a_created_fcdbcb_idx'),
        ),
    ]
